server:
  port: 8761
spring:
  application:
    name: erureka_server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: server1
    lease-expiration-duration-in-seconds: 45
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}