server:
  port: 8083
spring:
  application:
    name: merge
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 20000
  OkToRetryOnAllOperations: false
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 0
hystrix:
  threadpool:
    default:
      # 线程池大小
      coreSize: 200
      # 缓冲区大小， 如果为-1，则不缓冲，直接进行降级 fallback
      maxQueueSize: -1
      # 缓冲区大小超限的阈值，超限就直接降级
      queueSizeRejectionThreshold: 10
  command:
    default:
      execution:
        isolation:
          #执行策略
          # 资源隔离模式，默认thread。 SEMAPHORE为信号量，THREAD为线程池
          strategy: THREAD
          thread:
            # 超时时间，默认1000毫秒
            timeoutInMilliseconds: 3000
            # 超时时中断线程
            interruptOnTimeout: true
            # 取消时候中断线程
            interruptOnFutureCancel: false
        timeout:
          # 是否打开超时
          enabled: true
      # 拒绝策略
      fallback:
        # 是否开启服务降级
        enabled: true
        # fallback执行并发量
        isolation:
          semaphore:
            maxConcurrentRequests: 100
      # 熔断策略
      circuitBreaker:
        # 启用/禁用熔断机制
        enabled: true
        # 强制开启熔断
        forceOpen: false
        # 强制关闭熔断
        forceClosed: false
        # 前提条件，一定时间内发起一定数量的请求。  也就是10秒钟内(这个10秒对应下面的滚动窗口长度)至少请求4次，熔断器才发挥起作用。  默认20
        requestVolumeThreshold: 20
        # 错误百分比。达到或超过这个百分比，熔断器打开。  比如：10秒内有4个请求，2个请求超时或者失败，就会自动开启熔断
        errorThresholdPercentage: 50
        # 5秒后，进入半打开状态（熔断开启，间隔一段时间后，会让一部分的命令去请求服务提供者，如果结果依旧是失败，则又会进入熔断状态，如果成功，就关闭熔断）。 默认5秒
        sleepWindowInMilliseconds: 2000
#      # 度量策略
#      metrics:
#        rollingStats:
#          # 5秒为一次统计周期，术语描述：滚动窗口的长度为5秒
#          timeInMilliseconds: 5000
#          # 统计周期内 度量桶的数量，必须被timeInMilliseconds整除。作用：
#          numBuckets: 10
#        rollingPercentile:
#          # 是否收集执行时间，并计算各个时间段的百分比
#          enabled: true
#          # 设置执行时间统计周期为多久，用来计算百分比
#          timeInMilliseconds: 60000
#          rollingPercentile:
#            # 执行时间统计周期内，度量桶的数量
#            numBuckets: 6
#            # 执行时间统计周期内，每个度量桶最多统计多少条记录。设置为50，有100次请求，则只会统计最近的10次
#            bucketSize: 100
#        healthSnapshot:
#          # 数据取样时间间隔
#          intervalInMilliseconds: 500
#      # 设置是否缓存请求，request-scope内缓存
      requestCache:
        enabled: false
#      # 设置HystrixCommand执行和事件是否打印到HystrixRequestLog中
#      requestLog:
#        enabled: false
eureka:
  client:
    service-url:
      defaultZooe: http://169.254.56.187:8761/eureka/,http://169.254.56.187:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: '*'
